version: '3.3'
volumes:
  data:
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ../:/app:delegated
    ports:
      - '8000:80'
    networks:
      - my-network
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: yii2-app-restapi
    networks:
      - my-network
    volumes:
      - ./data:/var/lib/mysql
networks:
  my-network:
    driver: bridge